field.widget.settings.tagify_user_list_entity_reference_autocomplete_widget:
  type: field.widget.settings.tagify
  label: 'Tagify entity reference widget'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    match_limit:
      type: integer
      label: 'Maximum number of autocomplete suggestions'
    suggestions_dropdown:
      type: integer
      label: 'Suggestions dropdown'
    placeholder:
      type: string
      label: 'Placeholder'
    image:
      type: string
      label: 'Avatar image field'
    image_style:
      type: string
      label: 'Avatar image style'
    show_info_label:
      type: integer
      label: 'Include info label'
    info_label:
      type: string
      label: 'Info label content'
    show_entity_id:
      type: integer
      label: 'Include entity Id'
