<?php

declare(strict_types=1);

/**
 * @file
 * Functions to support theming in the tailpine theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function tailpine_preprocess_html(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function tailpine_preprocess_page(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function tailpine_preprocess_node(array &$variables): void {

}
