easy_email.settings:
  type: config_object
  label: 'Easy Email global settings'
  mapping:
    purge_on_cron:
      type: boolean
      label: 'Purge on cron'
    purge_cron_limit:
      type: integer
      label: 'Purge on cron limit'
    allowed_attachment_paths:
      type: sequence
      label: 'Allowed attachment paths'
      sequence:
          type: string
    email_collection_access:
      type: boolean
      label: 'Email report access'
    allowed_attachment_extensions:
      type: sequence
      label: 'Allowed attachment file extensions'
      sequence:
          type: string
    blocked_attachment_extensions:
      type: sequence
      label: 'Blocked attachment file extensions'
      sequence:
          type: string
    allowed_attachment_mime_types:
      type: sequence
      label: 'Allowed attachment MIME types'
      sequence:
          type: string
    blocked_attachment_mime_types:
      type: sequence
      label: 'Blocked attachment MIME types'
      sequence:
          type: string
    max_attachment_size:
      type: float
      label: 'Maximum attachment size in megabytes'
